2021/01/21 03:48:49 [crit] 521#521: *204 SSL_do_handshake() failed (SSL: error:141CF06C:SSL routines:tls_parse_ctos_key_share:bad key share) while SSL handshaking, client: 184.105.247.254, server: 0.0.0.0:443
2021/01/21 05:34:50 [crit] 521#521: *225 SSL_do_handshake() failed (SSL: error:141CF06C:SSL routines:tls_parse_ctos_key_share:bad key share) while SSL handshaking, client: 66.240.192.138, server: 0.0.0.0:443
2021/01/21 07:33:13 [error] 521#521: *251 client intended to send too large body: 4294967295 bytes, client: 176.58.124.134, server: dhbwdach.ddns.net, request: "GET /msdn.cpp HTTP/1.1", host: "93.235.96.177"
2021/01/21 08:42:07 [crit] 521#521: *275 SSL_do_handshake() failed (SSL: error:141CF06C:SSL routines:tls_parse_ctos_key_share:bad key share) while SSL handshaking, client: 192.241.219.72, server: 0.0.0.0:443
2021/01/21 10:51:48 [error] 523#523: *299 FastCGI sent in stderr: "Traceback (most recent call last):
  File "/var/www/html/scripts/dashboard_json.py", line 91, in <module>
    build_data_json(data_array)
  File "/var/www/html/scripts/dashboard_json.py", line 26, in build_data_json
    activ_uid = get_user_id(data_array)
  File "/var/www/html/scripts/files/get_data.py", line 59, in get_user_id
    return result[0][0]
IndexError: list index out of range" while reading response header from upstream, client: 93.235.96.177, server: dhbwdach.ddns.net, request: "POST /scripts/dashboard_json.py HTTP/1.1", upstream: "fastcgi://unix:/var/run/fcgiwrap.socket:", host: "dhbwdach.ddns.net", referrer: "https://dhbwdach.ddns.net/scripts/main.py"
2021/01/21 10:52:47 [error] 521#521: *317 FastCGI sent in stderr: "Traceback (most recent call last):
  File "/var/www/html/scripts/dashboard_json.py", line 91, in <module>
    build_data_json(data_array)
  File "/var/www/html/scripts/dashboard_json.py", line 26, in build_data_json
    activ_uid = get_user_id(data_array)
  File "/var/www/html/scripts/files/get_data.py", line 59, in get_user_id
    return result[0][0]
IndexError: list index out of range" while reading response header from upstream, client: 93.235.96.177, server: dhbwdach.ddns.net, request: "POST /scripts/dashboard_json.py HTTP/1.1", upstream: "fastcgi://unix:/var/run/fcgiwrap.socket:", host: "dhbwdach.ddns.net", referrer: "https://dhbwdach.ddns.net/scripts/main.py"
2021/01/21 23:13:41 [crit] 522#522: *62 SSL_do_handshake() failed (SSL: error:141CF06C:SSL routines:tls_parse_ctos_key_share:bad key share) while SSL handshaking, client: 93.174.95.106, server: 0.0.0.0:443
2021/01/21 23:17:04 [error] 522#522: *80 FastCGI sent in stderr: "PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/share/phpmyadmin/libraries/config/FormDisplay.php on line 660" while reading response header from upstream, client: 93.235.96.177, server: dhbwdach.ddns.net, request: "GET /phpmyadmin/index.php?token=33f78472003d385ceab7af7e7dd7d538 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "dhbwdach.ddns.net"
2021/01/21 23:18:10 [error] 522#522: *80 FastCGI sent in stderr: "Traceback (most recent call last):
  File "/var/www/html/scripts/main.py", line 88, in <module>
    show_homepage(data_array)
  File "/var/www/html/scripts/files/home_page.py", line 140, in show_homepage
    <tbody id="tabelle">"""
UnboundLocalError: local variable 'ident_value' referenced before assignment" while reading response header from upstream, client: 93.235.96.177, server: dhbwdach.ddns.net, request: "POST /scripts/main.py HTTP/1.1", upstream: "fastcgi://unix:/var/run/fcgiwrap.socket:", host: "dhbwdach.ddns.net", referrer: "https://dhbwdach.ddns.net/scripts/main.py"
